/* toki pona -> toki Kanse "Argot" | jan Sepulon */

dictionaries.jSepArgot = {
        'a' : '\'tain',
        'akesi' : 'dino',
		'ala' : 'que dalle',
		'alasa' : 'cherche',
		'ale' : 'total',
		'ali' : 'total',
		'anpa' : 'down',
		'ante' : 'modif',
		'anu' : 'ou',
		'awen' : 'reste',
		'e' : 'wesh',
		'en' : 'plus',
		'epiku' : 'd\'enfer',
		'esun' : 'bazar',
		'ijo' : 'machin',
		'ike' : 'pourri',
		'ilo' : 'bidule',
		'insa' : 'tripes',
		'jaki' : 'merde',
		'jan' : 'gnasse',
		'jasima' : 'verlan',
		'jelo' : 'pisse',
		'jo' : 'a',
		'kala' : 'poiscaille',
		'kalama' : 'boucan',
		'kama' : 'va',
		'kasi' : 'beuh',
		'ken' : 'peut',
		'kepeken' : 'avec',
		'kijetesantakalu' : 'gros rat',
		'kili' : 'fraise',
		'kin' : 'itou',
		'kipisi' : 'coupé',
		'kiwen' : 'caillou',
		'ko' : 'peuf',
		'kokosila' : 'dit nawak',
		'kon' : 'gaz',
		'ku' : 'gros bouquin',
		'kulupu' : 'bande',
        'kule' : 'couleur', 
		'kute' : 'esgourdé',
		'la' : 'ben alors',
		'lanpan' : 'chourré',
		'lape' : 'roupillon',
		'laso' : 'couleur schtroumpf',
		'lawa' : 'tronche',
		'leko' : 'Lego',
		'len' : 'fringue',
		'lete' : 'frigo',
		'li' : 'qui',
		'lili' : 'minus',
		'linja' : 'rail',
		'lipu' : 'bouquin',
		'loje' : 'sang',
		'lon' : 'sur',
		'luka' : 'paluche',
		'lukin' : 'zyeute',
		'lupa' : 'trou',
		'ma' : 'gadoue',
		'mama' : 'vioque',
		'mani' : 'thune',
		'meli' : 'meuf',
		'meso' : 'bof',
		'mi' : 'bibi',
		'mije' : 'mec',
		'misikeke' : 'médoc',
		'moku' : 'bouffe',
		'moli' : 'cané',
		'monsi' : 'cul',
		'monsuta' : 'trouille',
		'mu' : 'beuglé',
		'mun' : 'lune',
		'musi' : 'marrant',
		'mute' : 'une chiée',
		'n' : 'hmm',
		'namako' : 'kipik',
		'nanpa' : 'numéro',
		'nasa' : 'dingue',
		'nasin' : 'trace',
		'nena' : 'bosse',
		'ni' : 'ceci',
		'nimi' : 'nom',
		'noka' : 'peton',
		'o' : 'yo',
		'oko' : 'quinquet',
		'olin' : 'béguin',
		'ona' : 'iel',
		'open' : 'à la base',
		'pakala' : 'foutu',
		'pali' : 'boulot',
		'palisa' : 'tige',
		'pan' : 'graine',
		'pana' : 'fourgue',
		'pi' : 'de',
		'pilin' : 'sens',
		'pimeja' : 'keubla',
		'pini' : 'mort',
		'pipi' : 'bêbête',
		'poka' : 'côté',
		'poki' : 'sac',
		'pona' : 'top',
		'pu' : 'premier bouquin',
		'sama' : 'pareil',
		'seli' : 'hot',
		'selo' : 'couenne',
		'seme' : 'kesako',
		'sewi' : 'de Dieu',
		'sijelo' : 'graisse',
		'sike' : 'skeud',
		'sin' : 'tout frais',
		'sina' : 'tézigue',
		'sinpin' : 'face',
		'sitelen' : 'gribouillis',
		'soko' : 'champi',
		'sona' : 'pigé',
		'soweli' : 'bestiau',
		'suli' : 'maxi',
		'suno' : 'loupiotte',
		'supa' : 'planche',
		'suwi' : 'douceur',
		'tan' : 'à cause que',
		'taso' : 'seulement',
		'tawa' : 'bouge',
		'telo' : 'flotte',
		'tenpo' : 'à c\'t\'époque de',
		'toki' : 'baffouille',
		'tomo' : 'piaule',
		'tonsi' : 'non-binaire/trans',
		'tu' : '2',
		'unpa' : 'niqué',
		'uta' : 'gueule',
		'utala' : 'baston',
		'walo' : 'albinos',
		'wan' : '1',
		'waso' : 'piaf',
		'wawa' : 'fortiche',
		'weka' : 'tèj',
		'wile' : 'veux',
        'majuna': 'fossile',
        'powe' : 'fake',
        'isipin' : 'gamberge',
        'linluwi' : 'le net',
    };
