/* toki pona -> toki Kanse | jan Polijan */

dictionaries.jPolijan =
{
        'a' : 'ha',
        'akesi' : 'lézaroïde',
        'ala' : 'pas',
        'alasa' : 'recherche',
        'ale' : 'tout',
        'ali' : 'tous',
        'anpa' : 'en bas',
        'ante' : 'différent',
        'anu' : 'ou',
        'awen' : 'continué',
        'e' : 'du',
        'en' : 'et',
        'esun' : 'commerce',
        'ijo' : 'chose',
        'ike' : 'mauvais',
        'ilo' : 'outil',
        'insa' : 'intérieur',
        'jaki' : 'dégoutant',
        'jan' : 'personne',
        'jelo' : 'jaune',
        'jo' : 'détenir',
        'kala' : 'poisson',
        'kalama' : 'sonore',
        'kama' : 'devenir',
        'kasi' : 'végétal',
        'ken' : 'possible',
        'kepeken' : 'en utilisant',
        'kili' : 'fruit',
        'kiwen' : 'robuste',
        'ko' : 'mou',
        'kon' : 'éther',
        'kule' : 'coloré',
        'kulupu' : 'groupe',
        'kute' : 'ouïe',
        'la' : 'alors là',
        'lape' : 'dormir',
        'laso' : 'cyan',
        'lawa' : 'dirigeant',
        'len' : 'couverture',
        'lete' : 'froid',
        'li' : 'é',
        'lili' : 'petit',
        'linja' : 'ligne',
        'lipu' : 'feuille',
        'loje' : 'rouge',
        'lon' : 'situé à',
        'luka' : 'main',
        'lukin' : 'vue',
        'lupa' : 'trou',
        'ma' : 'territoire',
        'mama' : 'parent',
        'mani' : 'richesse',
        'meli' : 'féminine',
        'mi' : 'moi',
        'mije' : 'masculin',
        'moku' : 'aliment',
        'moli' : 'mort',
        'monsi' : 'arrière',
        'mu' : '"meuh"',
        'mun' : 'lune',
        'musi' : 'exaltant',
        'mute' : 'beaucoup',
        'nanpa' : 'numéro',
        'nasa' : 'étrange',
        'nasin' : 'voie',
        'nena' : 'protubérance',
        'ni' : 'ceci',
        'nimi' : 'nom',
        'noka' : 'pieds',
        'o' : 'ô',
        'olin' : 'amour',
        'ona' : 'iel',
        'open' : 'commencé',
        'pakala' : 'cassé',
        'pali' : 'œuvre',
        'palisa' : 'bâton',
        'pan' : 'céréalier',
        'pana' : 'émettre',
        'pi' : 'à',
        'pilin' : 'ressenti',
        'pimeja' : 'sombre',
        'pini' : 'fini',
        'pipi' : 'insecte',
        'poka' : 'côté',
        'poki' : 'récipient',
        'pona' : 'positif',
        'sama' : 'similaire',
        'seli' : 'chaud',
        'selo' : 'partie extérieure',
        'seme' : 'quoi?',
        'sewi' : 'élevé',
        'sijelo' : 'corps',
        'sike' : 'rond',
        'sin' : 'nouveau',
        'sina' : 'toi',
        'sinpin' : 'frontal',
        'sitelen' : 'symbole',
        'sona' : 'savoir',
        'soweli' : 'animal',
        'suli' : 'grandeur',
        'suno' : 'lumineux',
        'supa' : 'planche',
        'suwi' : 'doux',
        'tan' : 'à partir de',
        'taso' : 'seulement',
        'tawa' : 'vers',
        'telo' : 'liquide',
        'tenpo' : 'durée',
        'toki' : 'parler',
        'tomo' : 'chambre',
        'tu' : 'deux',
        'unpa' : 'sexuel',
        'uta' : 'bouche',
        'utala' : 'bataille',
        'walo' : 'pâle',
        'wan' : 'uni',
        'waso' : 'oiseau',
        'wawa' : 'fort',
        'weka' : 'eloigné',
        'wile' : 'voudrai',
        'kin' : 'aussi',
        'namako' : 'additionnel',
        'oko' : 'oeil',
        'tonsi' : 'non-cisnormatif',
        'ku' : 'dictionnaire du toki pona',
        'epiku' : 'épique',
        'jasima' : 'réflection',
        'kijetesantakalu' : 'raton laveur',
        'kipisi' : 'divisé',
        'kokosila' : 'pas en toki pona',
        'lanpan' : 'saisie',
        'leko' : 'carré',
        'meso' : 'moyen',
        'misikeke' : 'médicamental',
        'monsuta' : 'peur',
        'n' : 'euh',
        'soko' : 'champignon',
        'apeja' : 'déshonoré',
        'isipin' : 'pensée',
        'kapesi' : 'brunâtre',
        'kiki' : 'tranchant',
        'linluwi' : 'Internet',
        'majuna' : 'ancient',
        'mulapisu' : 'pizza',
        'pake' : 'bloqué',
        'powe' : 'faux',
        'samu' : 'désir de créer de nouveaux mots',
        'unu' : 'mauve',
        'wa' : 'woah',
        'yupekosi' : 'mauvaise mise à jour',
        'u' : 'mot réservé u',
        'ju' : 'mot réservé ju',
        'lu' : 'mot réservé lu',
        'nu' : 'mot réservé nu',
        'su' : 'mot réservé su',
        'ete' : 'au delà',
        'ewe' : 'roche',
        'kamalawala' : 'révolution',
        'kan' : 'avec',
        'ke' : 'okay',
        'kese' : 'LGBTQ+',
        'kulijo' : 'cool',
        'kuntu' : 'rire',
        'likujo' : 'collection',
        'loka' : 'membre',
        'misa' : 'rongeur',
        'neja' : 'quatre',
        'oke' : 'okay',
        'pata' : 'frère et sœur',
        'peto' : 'tristesse',
        'Pingo' : 'bagnole',
        'po' : 'quatre',
        'polinpin' : 'quille de bowling',
        'pomotolo' : 'efficace',
        'san' : 'trois',
        'soto' : 'à gauche',
        'sutopatikuna' : 'ornithorynque',
        'taki' : 'liant',
        'te' : '“',
        'teje' : 'à droite',
        'to' : '”',
        'tuli' : 'trois',
        'umesu' : 'épater la galerie',
        'usawi' : 'sorcellerie',
        'waleja' : 'contexte',
        'alu' : 'dans ce contexte:',
        'ki' : 'qui',
        'nimisin' : 'nouveau mot du toki pona',
        'puwa' : 'moelleux',
        'wiwi' : 'très volontiers',
        'olala' : 'oh là là',
        'panke' : 'franchouillard',
        'masalo' : 'mince alors',
        'sapelipope' : 'saperlipopette',
        'kalapisituji' : 'carabistouilles',
        'kikolo' : 'rigolo',
        'pipolo' : 'même pas drôle',
        'kikulo' : 'complètement immature',
        'sikako' : 'escargot',
        'kokoliko' : 'poulet',
        'apelo' : 'apéro',
        'kosikosa' : 'comme-ci comme-ça',
        'antikontitutonelema' : 'énorme désordre',
        'pu' : 'toki pona classique',
    };
