/* ante "relex": toki pona -> toki "kijetesantakalu"
 * nimi pi toki pona li kama lili sama nimi kijetesantakalu.
 * this covers all the nimi "UCSUR".
 *
 * Polijan: I did this, but many variations are possible. This ain't a very
 *          original idea, jan mute li musi sama kepeken nimi kijetesantakalu!
 */


// "lili" dictionary: nimi lili ni pi kepeken mute li awen sama:
//                    a, e, o, n, la, li, pi, mi, ni, ala
dictionaries.kijete_lili = {
'akesi'          : 'kijetesantakesi',
'alasa'          : 'kijetesantalasa',
'ale'            : 'kijetesantakale',
'ali'            : 'kijetesantakali',
'anpa'           : 'kijetesanpakalu',
'ante'           : 'kijetesantekalu',
'anu'            : 'kijetesantakanu',
'awen'           : 'kijetesantakawen',
'en'             : 'kijetesentakalu',
'esun'           : 'kijetesuntakalu',
'ijo'            : 'kijotesantakalu',
'ike'            : 'kiketesantakalu',
'ilo'            : 'kijetesantakilo',
'insa'           : 'kijetinsatakalu', // "wuwojiti" ala: 'kijesinsantakalu',
'jaki'           : 'kijakisantakalu',
'jan'            : 'kijetejantakalu',
'jelo'           : 'kijelosantakalu',
'jo'             : 'kijotesantakalu',
'kala'           : 'kijetesantakala',
'kalama'         : 'kijetesantakalama',
'kama'           : 'kijetesantakama',
'kasi'           : 'kijetesantakasi',
'ken'            : 'kijetekentakalu',
'kepeken'        : 'kikepekentakalu',
'kili'           : 'kilitesantakalu',
'kiwen'          : 'kiwentesantakalu',
'ko'             : 'kijetesantakolu',
'kon'            : 'kijetekontakalu',
'kule'           : 'kuletesantakalu',
'kulupu'         : 'kijetesankulupu', // anu: 'kulupusantakalu'
'kute'           : 'kikutesantakalu',
'lape'           : 'kijetesantakalape',
'laso'           : 'kijetesantakalaso',
'lawa'           : 'kijetesantakalawa',
'len'            : 'kijetelentakalu',
'lete'           : 'kiletesantakalu',
'lili'           : 'kijetesantalili',
'linja'          : 'kijetelinjakalu',
'lipu'           : 'kijetesantalipu',
'loje'           : 'lojetesantakalu',
'lon'            : 'kijetesantakalon',
'luka'           : 'kijetesanlukalu',
'lukin'          : 'kijetesantakalukin',
'lupa'           : 'kijetesantakalupa',
'ma'             : 'kijetesanmakalu',
'mama'           : 'kijetesanmamalu', // -ma after nasal vowel, heh?!
'mani'           : 'kijetemanikalu',
'meli'           : 'kimelisantakalu',
'mije'           : 'mijetesantakalu',
'moku'           : 'kijetesantamoku',
'moli'           : 'kijetesantamoli',
'monsi'          : 'kijetemonsikalu',
'mu'             : 'kijetesantakammmuuuuuuu',
'mun'            : 'kijetesantakamun',
'musi'           : 'kijemusitakalu',
'mute'           : 'kimutesantakalu',
'nanpa'          : 'kijetenanpakalu',
'nasa'           : 'kijetesanasalu',
'nasin'          : 'kijenasintakalu',
'nena'           : 'kijetesanenalu',
'nimi'           : 'nimijetesantakalu',
'noka'           : 'kijetesanokalu',
'olin'           : 'kijetesantakolin',
'ona'            : 'kijetesantonalu',
'open'           : 'kijetopentakalu',
'pakala'         : 'kijetesanpakala',
'pali'           : 'kijetesantapali',
'palisa'         : 'kijetepalisakalu',
'pan'            : 'kijetepantakalu',
'pana'           : 'kijetepanakalu',
'pilin'          : 'kijepilintakalu',
'pimeja'         : 'pimejatesantakalu',
'pini'           : 'kijetepinikalu',
'pipi'           : 'kijetepipikalu',
'poka'           : 'kijetesanpokalu',
'poki'           : 'kijetesanpokilu', // 'pokijetesantakalu',
'pona'           : 'kijeteponakalu',
'pu'             : 'kijetesantakapu',
'sama'           : 'kijetesamakalu',
'seli'           : 'kijetesantaseli',
'selo'           : 'kijetesantaselo',
'seme'           : 'kisemesantakalu',
'sewi'           : 'kijetesewikalu',
'sijelo'         : 'sijelosantakalu',
'sike'           : 'siketesantakalu',
'sin'            : 'kijetesintakalu',
'sina'           : 'kijetesinakalu',
'sinpin'         : 'kijetesinpinkalu',
'sitelen'        : 'kijetesansitelen',
'sona'           : 'kijetesonakalu',
'soweli'         : 'kijesowelikalu',
'suli'           : 'kijetesulikalu',
'suno'           : 'kijetesunokalu',
'supa'           : 'kijetesupakalu',
'suwi'           : 'kijetesuwikalu',
'tan'            : 'kijetetantakalu',
'taso'           : 'kijetesantasolu',
'tawa'           : 'kijetesantawalu',
'telo'           : 'kijetelosantakalu',
'tenpo'          : 'kijetenpotakalu',
'toki'           : 'kijetesantokilu',
'tomo'           : 'kijetesantomolu',
'tu'             : 'kijetusantakalu',
'unpa'           : 'kijetesunpakalu',
'uta'            : 'kijetesantakaluta',
'utala'          : 'kijetesanutalalu',
'walo'           : 'kijetesantawalo',
'wan'            : 'kijetewantakalu',
'waso'           : 'kijetewasotakalu',
'wawa'           : 'kijetesanwawalu',
'weka'           : 'kijetesantawekalu',
'wile'           : 'wiletesantakalu',
'namako'         : 'kijetenamakolu',
'kin'            : 'kinjetesantakalu',
'oko'            : 'kijetesantokolu',
'kipisi'         : 'kipisisantakalu',
'leko'           : 'kijetesanlekolu',
'monsuta'        : 'kijemonsutakalu',
'tonsi'          : 'kijetonsitakalu',
'jasima'         : 'kijetejasimalu',
'soko'           : 'kijetesokokalu',
'meso'           : 'kijemesotakalu',
'epiku'          : 'kijetesantepiku',
'kokosila'       : 'kikokosilakalu',
'lanpan'         : 'kijetelanpankalu',
'misikeke'       : 'kijemisikekelu',
'ku'             : 'kujetesantakalu',
'pake'           : 'kijetesanpakelu',
'apeja'          : 'kijetesantapeja',
'majuna'         : 'kijetemajunalu',
'powe'           : 'kijetesantapowe',
};


// the "ale" dictionary is also transforming the "little words"
dictionaries.kijete_ale = {
  ...dictionaries.kijete_lili,
  'a'  : 'kajetesantakalu',
  'ala': 'kijetesalakalu',
  'e'  : 'kejetesantakalu',
  'o'  : 'kijetesantakalo',
  'la' : 'kijetesantalalu',
  'li' : 'lijetesantakalu',
  'mi' : 'kijetemitakalu',
  'ni' : 'nijetesantakalu',
  'pi' : 'pijetesantakalu',
  'n'  : 'kijetesannntakalunnn',
};
