/* rajouter un petit commentaire ici:
 *  Pseudo-germanic
 *  par jan Sepulon
 */

dictionaries.pseudo_germanic = {
// nimi pu       :
'a'              : 'ach',
'akesi'          : 'Eckäsen',
'ala'            : 'nicht',
'alasa'          : 'Aläsen',
'ale'            : 'alle',
'ali'            : 'alle', // (peut-être le même rélex que pour ale)
'anpa'           : 'unter',
'ante'           : 'wechsöln',
'anu'            : 'oder',
'awen'           : 'wärtete',
'e'              : 'ein',
'en'             : 'und',
'esun'           : 'Märckt',
'ijo'            : 'etwös',
'ike'            : 'schlecht',
'ilo'            : 'Kräpfte',
'insa'           : 'gesämt',
'jaki'           : 'Kräß',
'jan'            : 'Zöft',
'jelo'           : 'jüschte',
'jo'             : 'hab',
'kala'           : 'Flische',
'kalama'         : 'Zuhörst',
'kama'           : 'gekommt',
'kasi'           : 'Pflänz',
'ken'            : 'könnte',
'kepeken'        : 'mit',
'kili'           : 'Frütchen',
'kiwen'          : 'Steinnen',
'ko'             : 'geschmückt',
'kon'            : 'gehießt',
'kule'           : 'Färbsche',
'kulupu'         : 'Sietzüngiemänschapf',
'kute'           : 'hörten',
'la'             : 'daß',
'lape'           : 'schläfften',
'laso'           : 'grüzbau',
'lawa'           : 'Köpfitzen',
'len'            : 'Läderpfosen',
'lete'           : 'gekaltet',
'li'             : 'zu',
'lili'           : 'kleiner',
'linja'          : 'Stiercke',
'lipu'           : 'Pflatt',
'loje'           : 'knöggi',
'lon'            : 'auf',
'luka'           : 'Händeln',
'lukin'          : 'gesiehen',
'lupa'           : 'Höschel',
'ma'             : 'Ärden',
'mama'           : 'Mutti',
'mani'           : 'Pfennige',
'meli'           : 'weiblisch',
'mi'             : 'ich',
'mije'           : 'männlisch',
'moku'           : 'Schmucken',
'moli'           : 'töd',
'monsi'          : 'Arscht',
'mu'             : 'klecki',
'mun'            : 'die Sternschnüfke',
'musi'           : 'Späß',
'mute'           : 'vielmal',
'nanpa'          : 'Nümmerei',
'nasa'           : 'verröckt',
'nasin'          : 'Sträße',
'nena'           : 'Blümpfitzen',
'ni'             : 'diese',
'nimi'           : 'Nahmer',
'noka'           : 'füßte',
'o'              : 'aus',
'olin'           : 'Liebeli',
'ona'            : 'sie',
'open'           : 'öpfne',
'pakala'         : 'Kraput',
'pali'           : 'Arbeitt',
'palisa'         : 'Schtecker',
'pan'            : 'Brötcheli',
'pana'           : 'gebt',
'pi'             : 'von',
'pilin'          : 'fehnen',
'pimeja'         : 'Schwörtze',
'pini'           : 'abgeschlößt',
'pipi'           : 'Schpünne',
'poka'           : 'im Nähekeit',
'poki'           : 'Töpfschon',
'pona'           : 'gelückt',
'pu'             : 'Wörtwissvertiefungen',
'sama'           : 'gleich',
'seli'           : 'warme',
'selo'           : 'Rumschlag',
'seme'           : 'was',
'sewi'           : 'Heimlige',
'sijelo'         : 'Schtruffe',
'sike'           : 'Ründ',
'sin'            : 'neuen',
'sina'           : 'du',
'sinpin'         : 'Mahersicht',
'sitelen'        : 'Ziechlen',
'sona'           : 'wiessenschopf',
'soweli'         : 'Zäugetiere',
'suli'           : 'größte',
'suno'           : 'die Sonnlitsch',
'supa'           : 'Truppä',
'suwi'           : 'süßli',
'tan'            : 'weil',
'taso'           : 'aber',
'tawa'           : 'Bewiege',
'telo'           : 'Waßer',
'tenpo'          : 'im Zeit',
'toki'           : 'Sprach',
'tomo'           : 'das Haus',
'tu'             : 'zwö',
'unpa'           : 'heckiflüßen',
'uta'            : 'Munt',
'utala'          : 'Kämpf',
'walo'           : 'Hörcke',
'wan'            : 'eins',
'waso'           : 'Vögli',
'wawa'           : 'Stärkft',
'weka'           : 'gefiebelt',
'wile'           : 'werden',
//
/////////////////////////////////////////////////////////////////
// nimi namako!                                                //
// wile sina la, o WEKA e ona anu o NAMAKO e nimi. ale li pona //
/////////////////////////////////////////////////////////////////
//
// nimi ku suli  :
'namako'         : 'Speiß',
'kin'            : 'auch',
'oko'            : 'Augen',
'kipisi'         : 'Messerung',
'leko'           : 'blöcht',
'monsuta'        : 'Angsch',
'jasima'         : 'gegenüber',
'kijetesantakalu': 'besser Bär',
'soko'           : 'Piltze',
'meso'           : 'Mitte',
'epiku'          : 'wunderbar',
'lanpan'         : 'zöhe',
'n'              : 'hmm',
'misikeke'       : 'Medizine',
'ku'             : 'ibuchläse',
//
// nimi ante (tan lawa "UCSUR")
'majuna'         : 'alte',
'powe'           : 'falsche',

// pfff t'as rien de mieux à faire que lire ces commentaires? ;)
};
