// toki pona   -> toki Satoko (GA, BU, ZO, MEU)
// toki Satoko -> toki pona
// see: https://www.youtube.com/watch?v=Sla57Zw-FN4
// (jan Polijan)

dictionaries.satoko_from = {
// 1 syllables (4)
'GA'           : 'la',
'BU'           : 'li',
'ZO'           : 'pi',
'MEU'          : 'e',
// 2 syllables (16)
'GAGA'         : 'mi',
'GABU'         : 'ala',
'GAZO'         : 'waso',
'GAMEU'        : 'ni',
'BUGA'         : 'ona',
'BUBU'         : 'lon',
'BUZO'         : 'mute',
'BUMEU'        : 'tan',
'ZOGA'         : 'tawa',
'ZOBU'         : 'ken',
'ZOZO'         : 'ale',
'ZOMEU'        : 'wile',
// 3 syllables (64)
'GAGAGA'       : 'pakala',
'GAGABU'       : 'kepeken',
'GAGAZO'       : 'kama',
'GAGAMEU'      : 'monsi',
'GABUGA'       : 'wawa',
'GABUBU'       : 'pona',
'GABUZO'       : 'en',
'GABUMEU'      : 'ilo',
'GAZOGA'       : 'suli',
'GAZOBU'       : 'awen',
'GAZOZO'       : 'tenpo',
'GAZOMEU'      : 'luka',
'GAMEUGA'      : 'toki',
'GAMEUBU'      : 'insa',
'GAMEUZO'      : 'ijo',
'GAMEUMEU'     : 'seme',
'BUGAGA'       : 'jan',
'BUGABU'       : 'telo',
'BUGAZO'       : 'anu',
'BUGAMEU'      : 'lipu',
'BUBUGA'       : 'a',
'BUBUBU'       : 'suwi',
'BUBUZO'       : 'lili',
'BUBUMEU'      : 'weka',
'BUZOGA'       : 'sona',
'BUZOBU'       : 'poka',
'BUZOZO'       : 'pali',
//'BUZOMEU'
'BUMEUGA'      : 'kiwen',
'BUMEUBU'      : 'sewi',
'BUMEUZO'      : 'lape',
'BUMEUMEU'     : 'lawa',
'ZOGAGA'       : 'lukin',
'ZOGABU'       : 'ma',
'ZOGAZO'       : 'nanpa',
'ZOGAMEU'      : 'anpa',
'ZOBUGA'       : 'kule',
'ZOBUBU'       : 'sama',
'ZOBUZO'       : 'nimi',
'ZOBUMEU'      : 'noka',
'ZOZOGA'       : 'pana',
'ZOZOBU'       : 'o',
'ZOZOZO'       : 'musi',
'ZOZOMEU'      : 'ante',
'ZOMEUGA'      : 'nena',
'ZOMEUBU'      : 'pini',
'ZOMEUZO'      : 'jo',
'ZOMEUMEU'     : 'alasa',
'MEUGAGA'      : 'nasa',
'MEUGABU'      : 'len',
'MEUGAZO'      : 'taso',
'MEUGAMEU'     : 'olin',
'MEUBUGA'      : 'moku',
'MEUBUBU'      : 'pilin',
'MEUBUZO'      : 'kasi',
'MEUBUMEU'     : 'sin',
'MEUZOGA'      : 'sina',
'MEUZOBU'      : 'seli',
'MEUZOZO'      : 'tomo',
'MEUZOMEU'     : 'ike',
'MEUMEUGA'     : 'open',
'MEUMEUBU'     : 'soweli',
'MEUMEUZO'     : 'kili',
'MEUMEUMEU'    : 'mu',
// 4 syllables
'GAGABUZO'     : 'mije',
'GAGAMEUGA'    : 'meli',
'GAGAZOMEU'    : 'tonsi',
'GAGABUBU'     : 'utala',
'GAZOGAZO'     : 'mama',
'GAZOMEUMEU'   : 'sitelen',
'GAZOZOMEU'    : 'kala',
'GABUGABU'     : 'kulupu',
'GAMEUZOMEU'   : 'uta',
'BUGABUGA'     : 'unpa',
'BUGAGABU'     : 'palisa',
'BUGAZOBU'     : 'supa',
'BUGAMEUGA'    : 'pan',
'BUGAZOZO'     : 'loje',
'BUGAZOGA'     : 'lupa',
'BUBUGAGA'     : 'lete',
'BUBUZOBU'     : 'jelo',
'BUMEUGAGA'    : 'poki',
'BUBUMEUMEU'   : 'kalama',
'BUMEUZOGA'    : 'mani',
'BUZOGAGA'     : 'wan',
'BUZOMEUMEU'   : 'tu',
'BUZOBUZO'     : 'linja',
'BUBUZOZO'     : 'pimeja',
'ZOGABUMEU'    : 'esun',
'ZOGAMEUMEU'   : 'mun',
'ZOBUGAGA'     : 'selo',
'ZOBUGAMEU'    : 'jaki',
'ZOBUBUMEU'    : 'walo',
'ZOZOGAZO'     : 'pipi',
'ZOZOBUMEU'    : 'sike',
'ZOMEUGAMEU'   : 'sinpin',
'ZOMEUBUBU'    : 'ko',
'MEUZOBUBU'    : 'nasin',
'MEUZOGAZO'    : 'kon',
'MEUZOGABU'    : 'moli',
'MEUGAMEUZO'   : 'sijelo',
'MEUMEUBUZO'   : 'laso',
'MEUMEUGABU'   : 'kute',
'MEUMEUMEUMEU' : 'pu',
'MEUZOZOMEU'   : 'akesi',
// namako (ku suli, etc.)
'GBZ':'n',
'BUZOMEU':'kin',
'GABUZOBUMEUMEUGABUZOGABU':'kijetesantakalu',
'MEUMEUGAGA':'misikeke',
'ZOGAMEUGA':'soko',
'MEUZOMEUZO':'meso',
'MEUBUGAMEU':'epiku',
'ZOZOBUGA':'kokosila',
'ZOBUZOMEU':'lanpan',
'MEUMEUMEUBU':'ku',
'BUMEUZOMEU':'majuna',
'GAMEUGABU':'powe',
'GABUZOMEU':'namako',
'ZOGAGAMEU':'oko',
'ZOBUBUGA':'kipisi',
'ZOGABUGA':'leko',
'GAGABUGA':'monsuta',
'BUMEUGAZO':'jasima',
};

dictionaries.satoko_to = {
// 1
'la':'GA',
'li':'BU',
'pi':'ZO',
'e':'MEU',
// 2
'ona':'BUGA',
'ala':'GABU',
'waso':'GAZO',
'ni':'GAMEU',
'mi':'GAGA',
'lon':'BUBU',
'mute':'BUZO',
'tan':'BUMEU',
'tawa':'ZOGA',
'ken':'ZOBU',
'ale':'ZOZO',
'ali':'ZOZO',
'wile':'ZOMEU',
// 3
'pakala':'GAGAGA',
'kepeken':'GAGABU',
'kama':'GAGAZO',
'monsi':'GAGAMEU',
'wawa':'GABUGA',
'pona':'GABUBU',
'en':'GABUZO',
'ilo':'GABUMEU',
'suli':'GAZOGA',
'awen':'GAZOBU',
'tenpo':'GAZOZO',
'luka':'GAZOMEU',
'toki':'GAMEUGA',
'insa':'GAMEUBU',
'ijo':'GAMEUZO',
'seme':'GAMEUMEU',
'jan':'BUGAGA',
'telo':'BUGABU',
'anu':'BUGAZO',
'lipu':'BUGAMEU',
'a':'BUBUGA',
'suwi':'BUBUBU',
'lili':'BUBUZO',
'weka':'BUBUMEU',
'sona':'BUZOGA',
'poka':'BUZOBU',
'pali':'BUZOZO',
// 'BUZOMEU'
'kiwen':'BUMEUGA',
'sewi':'BUMEUBU',
'lape':'BUMEUZO',
'lawa':'BUMEUMEU',
'lukin':'ZOGAGA',
'ma':'ZOGABU',
'nanpa':'ZOGAZO',
'anpa':'ZOGAMEU',
'kule':'ZOBUGA',
'sama':'ZOBUBU',
'nimi':'ZOBUZO',
'noka':'ZOBUMEU',
'pana':'ZOZOGA',
'o':'ZOZOBU',
'musi':'ZOZOZO',
'ante':'ZOZOMEU',
'nena':'ZOMEUGA',
'pini':'ZOMEUBU',
'jo':'ZOMEUZO',
'alasa':'ZOMEUMEU',
'nasa':'MEUGAGA',
'len':'MEUGABU',
'taso':'MEUGAZO',
'olin':'MEUGAMEU',
'moku':'MEUBUGA',
'pilin':'MEUBUBU',
'kasi':'MEUBUZO',
'sin':'MEUBUMEU',
'sina':'MEUZOGA',
'seli':'MEUZOBU',
'tomo':'MEUZOZO',
'ike':'MEUZOMEU',
'open':'MEUMEUGA',
'soweli':'MEUMEUBU',
'kili':'MEUMEUZO',
'mu':'MEUMEUMEU',
// 4
'mije':'GAGABUZO',
'meli':'GAGAMEUGA',
'tonsi':'GAGAZOMEU',
'utala':'GAGABUBU',
'mama':'GAZOGAZO',
'sitelen':'GAZOMEUMEU',
'kala':'GAZOZOMEU',
'kulupu':'GABUGABU',
'uta':'GAMEUZOMEU',
'unpa':'BUGABUGA',
'palisa':'BUGAGABU',
'supa':'BUGAZOBU',
'pan':'BUGAMEUGA',
'loje':'BUGAZOZO',
'lupa':'BUGAZOGA',
'lete':'BUBUGAGA',
'jelo':'BUBUZOBU',
'poki':'BUMEUGAGA',
'kalama':'BUBUMEUMEU',
'mani':'BUMEUZOGA',
'wan':'BUZOGAGA',
'tu':'BUZOMEUMEU',
'linja':'BUZOBUZO',
'pimeja':'BUBUZOZO',
'esun':'ZOGABUMEU',
'mun':'ZOGAMEUMEU',
'selo':'ZOBUGAGA',
'jaki':'ZOBUGAMEU',
'walo':'ZOBUBUMEU',
'pipi':'ZOZOGAZO',
'sike':'ZOZOBUMEU',
'sinpin':'ZOMEUGAMEU',
'ko':'ZOMEUBUBU',
'nasin':'MEUZOBUBU',
'kon':'MEUZOGAZO',
'moli':'MEUZOGABU',
'sijelo':'MEUGAMEUZO',
'laso':'MEUMEUBUZO',
'kute':'MEUMEUGABU',
'pu':'MEUMEUMEUMEU',
'akesi':'MEUZOZOMEU',
// namako (ku suli, etc.)
'ali'            : 'ZOZOZO',
'n'              : 'GBZ',
'kin'            : 'BUZOMEU',
'kijetesantakalu': 'GABUZOBUMEUMEUGABUZOGABU',
'misikeke'       : 'MEUMEUGAGA',
'soko'           : 'ZOGAMEUGA',
'meso'           : 'MEUZOMEUZO',
'epiku'          : 'MEUBUGAMEU',
'kokosila'       : 'ZOZOBUGA',
'lanpan'         : 'ZOBUZOMEU',
'ku'             : 'MEUMEUMEUBU',
'majuna'         : 'BUMEUZOMEU',
'powe'           : 'GAMEUGABU',
'namako'         : 'GABUZOMEU',
'oko'            : 'ZOGAGAMEU',
'kipisi'         : 'ZOBUBUGA',
'leko'           : 'ZOGABUGA',
'monsuta'        : 'GAGABUGA',
'jasima'         : 'BUMEUGAZO',
};
