/* toki simon (monsi) - some kind of "verlan" for toki pona / by jan Polijan */

dictionaries.simon = {
// 'a'            : 'a',
   'akesi'        : 'esika',
   'alasa'        : 'asala',
   'ale'          : 'ela',
   'ali'          : 'ila',
   'ante'         : 'tena',
   'anu'          : 'una',
   'awen'         : 'newa',
// 'e'            : 'e',
// 'en'           : 'ne',
   'esun'         : 'nuse',
   'ijo'          : 'oji',
   'ike'          : 'eki',
   'ilo'          : 'oli',
   'insa'         : 'sani',
   'jaki'         : 'kija',
   'jan'          : 'naju',
   'kala'         : 'laka',
   'kalama'       : 'malaka',
   'kama'         : 'maka',
   'kasi'         : 'sika',
   'ken'          : 'neku',
   'kepeken'      : 'kenpeke',
   'kili'         : 'liki',
   'kiwen'        : 'wenki',
   'kon'          : 'noku',
   'kule'         : 'leku',
   'kulupu'       : 'puluku',
   'kute'         : 'teku',
// 'la'           : 'la',
   'lape'         : 'pela',
   'laso'         : 'sola',
   'lawa'         : 'wala',
   'len'          : 'nelu',
   'lete'         : 'tele',
// 'li'           : 'li',
// 'lili'         : 'lili',
   'linja'        : 'jalin',
   'lipu'         : 'puli',
   'loje'         : 'jel\'o',
   'jelo'         : 'l\'oje',
// 'lon'          : 'nol\'u',
   'luka'         : 'kalu',
   'lukin'        : 'kinlu',
   'lupa'         : 'palu',
// 'ma'           : 'amu',
// 'mama'         : 'mama',
   'mani'         : 'nima',
   'meli'         : 'lime',
// 'mi'           : 'imu',
   'mije'         : 'jemi',
   'moku'         : 'kumo',
   'moli'         : 'limo',
   'monsi'        : 'simon',
// 'mu'           : 'mu',
   'mun'          : 'numu',
   'musi'         : 'simu',
   'mute'         : 'temu',
   'nanpa'        : 'panan',
   'nasa'         : 'sana',
   'nasin'        : 'nisan',
   'nena'         : 'nane',
   'ni'           : 'in',
   'nimi'         : 'mini',
   'noka'         : 'kano',
// 'o'            : 'o',
   'olin'         : 'lino',
   'ona'          : 'ano',
   'open'         : 'nepo',
   'pakala'       : 'lakapa',
   'pali'         : 'lipa',
   'palisa'       : 'salipa',
   'pan'          : 'napu',
   'pana'         : 'napa',
   'anpa'         : 'pana',
// 'pi'           : 'ipu',
   'pilin'        : 'linpi',
   'pimeja'       : 'jamepi',
   'pini'         : 'nipi',
// 'pipi'         : 'pipi',
   'poka'         : 'kapo',
   'poki'         : 'kipo',
   'pona'         : 'napo',
// 'pu'           : 'upu',
   'sama'         : 'masa',
   'seli'         : 'lise',
   'selo'         : 'lose',
   'seme'         : 'mese',
   'sewi'         : 'wise',
   'sijelo'       : 'lojesi',
   'sike'         : 'kesi',
   'sin'          : 'nisu',
   'sina'         : 'nasi',
   'sinpin'       : 'pinsin',
   'sitelen'      : 'lentesi',
   'sona'         : 'naso',
   'soweli'       : 'liweso',
   'suli'         : 'lisu',
   'suno'         : 'nosu',
   'supa'         : 'pasu',
   'suwi'         : 'wisu',
 // 'tan'         : 'nat\'u',
   'taso'         : 'sota',
   'tawa'         : 'wata',
   'telo'         : 'lote',
   'tenpo'        : 'poten', // ponte
   'toki'         : 'kito',
   'tomo'         : 'moto',
// 'tu'           : 'tu',
   'unpa'         : 'panu',
   'uta'          : 'atu',
   'utala'        : 'latalu',
   'walo'         : 'lowa',
   'wan'          : 'uni',
   'waso'         : 'sowa',
//  'wawa'        : 'wawa',
   'weka'         : 'kawe',
   'wile'         : 'lewi',
   'kin'          : 'niku',
   'namako'       : 'konama',
// 'oko'          : 'oko',
   'tonsi'        : 'siton',
// 'ku'           : 'ku',
   'epiku'        : 'kupine',
   'jasima'       : 'masija',
   'kijetesantakalu' : 'lukatasantejeki',
   'kipisi'       : 'sipiki',
   'kokosila'     : 'silakoko',
   'lanpan'       : 'panlan',
   'leko'         : 'kole',
   'meso'         : 'semo',
   'misikeke'     : 'kekesimi',
   'monsuta'      : 'tasumon',
// 'n'            : 'n',
   'soko'         : 'koso',
   'majuna'       : 'najuma',
   'apeja'        : 'ajepa',
};
