/* toki pona li kama sama sitelen pi toki Kanse
 * jan pali: jan Polijan
 */

dictionaries.sitelen_panke = {
'a'              : 'ha',
'la'             : 'là',
'n'              : 'hmmm',
'akesi'          : 'acquésci',
'ala'            : 'à la',
'alasa'          : "alla sa",
'ale'            : 'allez',
'ali'            : 'allie',
'anpa'           : 'Anne pas',
'ante'           : 'âne thé',
'anu'            : 'à nous',
'awen'           : 'aouenne',
'e'              : 'et',
'en'             : 'haine',
'esun'           : 'éssounne',
'ijo'            : 'hiyaux',
'ike'            : 'icquer',
'ilo'            : 'îlot',
'insa'           : 'hine ça',
'jaki'           : "y'a qui",
'jan'            : 'Yann',
'jelo'           : 'yélaux',
'jo'             : 'yaux',
'kala'           : "qu'à la",
'kalama'         : 'câlammas',
'kama'           : 'cas ma',
'kasi'           : "qu'à si",
'ken'            : "quennes",
'kepeken'        : 'quai péquenne',
'kili'           : 'qui lit',
'kiwen'          : 'qui ouenne',
'ko'             : 'caux',
'kon'            : 'conne',
'kule'           : 'couler',
'kulupu'         : 'coups loupoux',
'kute'           : 'coûté',
'lape'           : 'la paix',
'laso'           : 'la seau',
'lawa'           : 'la ouah',
'len'            : 'laine',
'lete'           : "l'été",
'li'             : 'lit',
'lili'           : "l'ylie",
'linja'          : "Lynne y'a",
'lipu'           : "l'ipoux",
'loje'           : 'lôt y est',
'lon'            : "l'aune",
'luka'           : "loup qu'a",
'lukin'          : 'louquine',
'lupa'           : 'loup pas',
// 'ma'          : 'ma',
'mama'           : 'mamma',
'mani'           : 'manie',
'meli'           : 'mélie',
'mi'             : 'mis',
'mije'           : 'millet',
'moku'           : 'meaucoup',
'moli'           : 'mollit',
'monsi'          : 'maune si',
'mu'             : 'mou',
'mun'            : 'mounne',
'musi'           : 'moussit',
'mute'           : 'moutez',
'nanpa'          : "n'âne pas",
'nasa'           : 'nassat',
'nasin'          : 'nacine',
'nena'           : "n'ainat",
'ni'             : 'nid',
'nimi'           : "n'imit",
'noka'           : 'nauquat',
'o'              : 'eau',
'olin'           : "haut l'inne",
'ona'            : 'aunas',
'open'           : 'haut peine',
'pakala'         : 'pas cala',
'pali'           : 'pâlie',
'palisa'         : 'pas lissa',
'pan'            : 'panne',
'pana'           : 'pannat',
'pi'             : 'pis',
'pilin'          : 'pilinne',
'pimeja'         : 'pimeilla',
'pini'           : 'pinit',
// 'pipi'        : 'pipi',
'poka'           : "peau qu'a",
'poki'           : 'peau qui',
'pona'           : 'paunnat',
'pu'             : 'poux',
'sama'           : "ça m'a",
'seli'           : "ses lits",
'selo'           : "c'est l'eau",
'seme'           : "s'aimer",
'sewi'           : "c'est oui",
'sijelo'         : "scié l'eau",
'sike'           : 'six quais',
'sin'            : 'sinne',
'sina'           : "s'inat",
'sinpin'         : 'sine-pinne',
'sitelen'        : "citée l'haine",
'sona'           : 'sauna',
'soweli'         : 'saut ouélit',
'suli'           : 'sous-lit',
'suno'           : 'sous nos',
'supa'           : 'sous pas',
'suwi'           : 'sous oui',
'tan'            : 'tanne',
'taso'           : 'tasse au',
'tawa'           : 'ta ouah',
'telo'           : "thé l'eau",
'tenpo'          : 'thène pôt',
'toki'           : 'tôt qui',
'tomo'           : 'tôt maux',
'tu'             : 'toux',
'unpa'           : 'oune pas',
'uta'            : 'ou ta',
'utala'          : "où t'as la",
'walo'           : 'houalôt',
'wan'            : 'ouanne',
'waso'           : 'oisseaux',
'wawa'           : 'ouah-ouah',
'weka'           : 'ouais cas',
'wile'           : 'oui laid',
'namako'         : 'namaqueau',
'kin'            : 'quine',
'oko'            : 'hoqueaux',
'kipisi'         : 'qui pissit',
'leko'           : "l'écaux",
'monsuta'        : 'maune sous ta',
'tonsi'          : 'tonne si',
'jasima'         : "y'a six mâts",
'kijetesantakalu': "qui-était sane t'as qu'à loup",
'soko'           : 'soqueau',
'meso'           : 'mes seaux',
'epiku'          : 'épique où',
'kokosila'       : 'coco si la',
'lanpan'         : 'la neupanne',
'misikeke'       : 'myciqué quai',
'ku'             : 'coût',
'pake'           : 'paquet',
'apeja'          : 'apeilla',
'majuna'         : 'maillounat',
'powe'           : 'pôt ouais',
};
