/* mi namako e nimi pi toki pona kepeken nasin nasa Unicode
 * tan: jan Polijan
 */

dictionaries.uniko_musi = {
// nimi pu       :
'a'              : 'a̍',
'akesi'          : '≡äkësï≡',
'ala'            : 'a̶l̶a',
'alasa'          : 'ala̶s̶a̶→',
'ale'            : '⒜l⒠',
'ali'            : '⒜l⒤',
'anpa'           : 'ɐduɐ',
'ante'           : 'ᵃₙᵀₑ',
'anu'            : 'ᵃₙᵘ',
'awen'           : 'ᴀᴡᴇɴ',
'e'              : '🅔',
'en'             : '🙵ₙ',
'esun'           : '€$UN',
'ijo'            : 'ij◯',
'ike'            : '𐌉𐌊𐌄', // ȋ̇̈k̑̇̈ȇ̇̈
'ilo'            : '🬸🬐🬲🬏🬴▌',
'insa'           : 'i̲̅n̲̅s̲̅a̲̅',
'jaki'           : 'j̶᷊̯̠̾᷅͝a̷᷂͈᷊᷁ͯ͘k̸͔᷊̻̐᷁̚í̷̭̘̙̍͒',
'jan'            : 'ⱼⱭₙ',
'jelo'           : 'j🟨lo',
'jo'             : 'jo̊',
'kala'           : 'kàl̗ä',
'kalama'         : 'kala♫a',
'kama'           : 'ₖ𝑎𝑚ᵃ',
'kasi'           : '𝕜𝕒𝕤𝕚',
'ken'            : '𝓚en',
'kepeken'        : '𝔨𝔢𝔭𝔢𝔨𝔢𝔫',
'kili'           : 'kìli',
'kiwen'          : 'k⃟i⃟w⃟e⃟n⃟',
'ko'             : '𝕜𝕠',
'kon'            : 'k͛o͛n͛',
'kule'           : '🌈𝓴𝓾𝓵𝓮🌈',
'kulupu'         : 'külüpü',
'kute'           : 'ᕮkuteᕭ',
'la'             : '🅛🅐',
'lape'           : '▓▒LΛPΞ▒░',
'laso'           : 'l🟦s🟩',
'lawa'           : 'läwa',
'len'            : '█▒l▓e▓n▒█',
'lete'           : '𝔩𝔢𝔱𝔢',
'li'             : '🅛🅘',
'lili'           : 'ₗᵢₗᵢ',
'linja'          : 'liñja',
'lipu'           : '⌜𝚕𝚒𝚙𝚞⌟',
'loje'           : 'l🟥je',
'lon'            : 'l̲o̲n̲', //'l̲☉n̲',
'luka'           : 'l🯁u🯂k🯃a',
'lukin'          : 'lükin',
'lupa'           : 'l⋃pa',
'ma'             : 'MⰡ', // 'ꙚⰡ', // 'MⰡ',
'mama'           : 'mḁmḁ',
'mani'           : '₥₳₦I',
'meli'           : 'ℳℰℒℐ',
'mi'             : '𝗺𝗶',
'mije'           : '🬝▌🬸🬐🬱▌█🬐', // '┏┳┓┃┛𝗘',
'moku'           : 'm⬭ku',
'moli'           : '(ₘo⃰ₗi⃰)',
'monsi'          : '·[monsi]',
'mu'             : '𝕸𝖀',
'mun'            : '⡗⠔⡇⢇⡸⡗⢼',
'musi'           : '☺musi☺',
'mute'           : 'mͫuͧtͭeͤ',
'nanpa'          : '𝙽#𝙽𝙿𝙰',
'nasa'           : 'N@S@',
'nasin'          : 'nasᛣn',
'nena'           : 'ՈeՈa',
'ni'             : 'n↓',
'nimi'           : '[𝚗𝚒𝚖𝚒]',
'noka'           : 'ₙₒₖₐ', // 'Lₙₒₖₐᕊ',
'o'              : 'o̍',
'olin'           : '♡lin',
'ona'            : 'ᓄna',
'open'           : '╘ₒₚₑₙ╛',
'pakala'         : '𐌓𐌀𐌊𐌀𐌋𐌀',
'pali'           : 'PALI',
'palisa'         : 'pal│sa',
'pan'            : 'pǎ̴̬̌̌n',
'pana'           : 'p`á´n`à´',
'pi'             : 'ⓟⓘ',  //'🅟🅘',
'pilin'          : '¡𝓅𝒾𝓁𝒾𝓃!',
'pimeja'         : 'p⬛meja',
'pini'           : 'pエnエ',
'pipi'           : 'pÏpÏ',
'poka'           : '𝑝𝑜𝑘𝑎',
'poki'           : '🄿🄾🄺🄸',
'pona'           : 'p̐̈ǒn̐̈ǎ',
// 'pu'          : 'pu',
'sama'           : 's=a=m=a',
'seli'           : 'sel\i/',
'selo'           : '𝕤𝕖𝕝𝕠',
'seme'           : '¿seme?',
'sewi'           : '🭻s🭺e🭹ᘈ🭸ⁱ🭷', // 'ˢᵉʷⁱ',
'sijelo'         : '╒sij╤elo╕',
'sike'           : 'ⓢⓘⓚⓔ',    //'⣊⠅⣹⡁⡧⢎⣟⡁',
'sin'            : '-sⁱn-',
'sina'           : '𝘀𝗶𝗻𝗮',
'sinpin'         : '[sinpin]·',
'sitelen'        : '𝓼𝓲𝓽𝓮𝓵𝓮𝓷',
'sona'           : '𝚜`□´𝚗𝚊',
'soweli'         : 'sö̖w̖e̖l̖i',
'suli'           : 'ＳＵＬＩ',
'suno'           : 'sun-ߦ-',
'supa'           : '┬supa┬',
'suwi'           : 'sûwî',
'tan'            : 'ᵗa⃖ₙ',
'taso'           : '𝈅ᗆഗo',
'tawa'           : '🮲tawa🮳',
'telo'           : 't̫͂e̫͂l̫͂o̫͂',
'tenpo'          : 'tenp◷',
'toki'           : 't`O̍´ki',
'tomo'           : 'T⌂M⌂',
'tu'             : 'tͭuͧ',
'unpa'           : 'UNPA',
'uta'            : 'ᗜ⊤ᗩ',
'utala'          : '𝖚𝖙𝖆𝖑𝖆',
'walo'           : 'w⬜lo',
'wan'            : 'ᗯᗅᖿ',
'waso'           : 'ẁäsó',
'wawa'           : '\\𝘄𝗮𝘄𝗮/',
'weka'           : '⠀̗̀weka⠀̖́',
'wile'           : 'ωilε',
//
/////////////////////////////////////////////////////////////////
// nimi namako!                                                //
// wile sina la, o WEKA e ona anu o NAMAKO e nimi. ale li pona //
/////////////////////////////////////////////////////////////////
//
// nimi ku suli  :
'namako'         : 'ñå𝓶ä𝓴ö',
'kin'            : 'k¡n',
'oko'            : 'ʘKʘ',
'kipisi'         : 'k̷i̷p̷i̷s̷i̷',
'leko'           : '🄻🄴🄺🄾', // 🬲🬏█🬐🬛🬐🬴▌
'monsuta'        : '╱╲╱╲𝕺𝕹𝕾𝖀𝕿𝕬',
'tonsi'          : 'T`Ϙ´NSI',
'jasima'         : 'ɐɯısɐɾ',
'kijetesantakalu': 'kijetesantakalü̧',
'soko'           : 's⍾k⍾',
'meso'           : 'mᴇso',
'epiku'          : '𝕰𝖕𝖎𝖐𝖀',
'kokosila'       : 'køkøsila',
'lanpan'         : '𝔩𝔞𝔫𝔭𝔞𝔫',
'n'              : 'n̍',
'misikeke'       : '(ᴍɪsɪ┊ᴋᴇᴋᴇ)',
'ku'             : 'kû',
// nimi ante (tan lawa "UCSUR")
'majuna'         : '-𝓂𝒶ⱼ𝓊𝓃𝒶-',
'powe'           : 'p⃠o⃠w⃠e⃠',
'apeja'          : 'a⃠p⃠e⃠j⃠a⃠',
'pake'           : 'p⃠a⃠k⃠e⃠',
// nimi musi panke (tan kulupu pona pi toki Kanse)
'wiwi'           : '𝓦𝓲𝓦𝓲',
'olala'          : '𝒪ₗᵃₗᵃ',
'panke'          : 'pǎ̴̬̌̌n𝓴𝓮',
'masalo'         : '𝓜𝓪𝓼𝓪𝓵◯',
'sapelipope'     : '𝓢𝓪𝓹𝓮𝓵𝓲𝓹𝓸𝓹𝓮',
'kalapisituwi'   : 'k⃠a⃠l⃠a⃠p⃠i⃠s⃠i⃠t⃠u⃠w⃠i⃠',
'kalapisituji'   : 'k⃠a⃠l⃠a⃠p⃠i⃠s⃠i⃠t⃠u⃠j⃠i⃠',
'kikolo'         : 'kik☺l☺',
'pipolo'         : '𝚙𝚒𝚙𝚘𝚕𝚘',
'kikulo'         : '𝓴𝓲𝓴𝓾𝓵𝓸ₗ',
'sikako'         : 'SIₖₐₖₒ𝀃',
'kokoliko'       : ',ₖᵒᵏᵒˡⁱᵏᵒ>',
'apelo'          : 'åpéʆo̲',
'kosikosa'       : '≃kosi≃kosa≃',
'antikontitutonelema': 'ą̷̞̳͕̪̞̬̳᷂̠̘̗̰̤᷊͓̖̹̬̖͔͇̺͂̓́̆̌͒͢͟͞n̷̡̞̪̱̳̦ͪ︢͛͊᷅ͨ̋͒̇̑͐̕t̸̢̨̡̨̲̠̪̞͉̤̙͕͇͈̝͇͑͂͌ͨͧͭ᷾̀᷈̐̈́̓͢͢͢i̶̛̪͈̻̞̱̲᷂᷂ͫ᷾͛̎̀︢̔̑͊ͮ̀᷃᷅̉ͬ́͒᷾̑᷁̈̇ͩ̚̕̕͘͞͝k̸͇̯̝̖͓̬͚̱̣̼᷿ͨ̓̏ͣ̇̉̀͊́̾̈᷉̇ͥ͐̿̍͐ͤ︠͋͜͜͞͠ǫ̶̡̢̧̨̧͖̯̳̲̟͇̳̮͎͕͓͚̘͎̯̳̟᷿̩̳͖̱̂͆ͧ᷾ͣ̈́︣ͭ͒ͩ᷈᷉ͭ̐̿̽᷁᷁᷉͘̚͜͜͠n̸̢̛᷿̼̖̖̺̺᷿̫͂͆᷉᷆͐᷇͑᷇ͯ᷈ͮ̾᷈̈᷅́̇̂ͩ᷈᷈͐᷇ͣ͘̚͠ţ̴̙̗͖̩̫͕̬̘̹̳̜̙̭͉̤̹̯̭̞̜̼̲̭̮ͧ͑̓̂ͮ᷃̋᷃̔̔͐᷾̑᷄͛͗͆︣̏̽̃͂͛᷉͢͟͜͞i̶̢̹̦̟̻̟̘̦᷿̮̻̙͔̯̝͈̘͔͕̤̰͓̻̼̻ͯ̄ͦ͟͢͟͢t̸̢̨̛᷊̪̲̘̫̼͕̩̫̳̦̼̭̱̰͓̤͎̗̦͎̦̤̮̗᷿̩᷀᷅̍̅̌̎ͬ︣᷇᷀ͫ᷈̋᷉͒̀̅̄̇ͨ᷄̚͘͠͡ụ̵̘͉͕͚̯̗͎͓͓̱̜̝̖͎̰̘͇̞̰ͪͤͥ͟t̶̡̛̠͔̞̞͈̘͕᷿ͬ᷀ͮͥ́͢o̶̟̠͕͌᷈̆̆ͦ̍᷇̈͌︣︢ͩ̉͌̃ͫͭ͞n̷̡̡̧̲͚̯̼̬̖̜̼̞̞̲̻̳͕͕̮͔᷊̬᷂̼̞᷿͆᷆͂̎͜͟͢ȅ̷̡̧̧̡̦̜̲̳̝̗͉̲̞̖̘̮̯̼͖̎ͫ̈́͋ͥ̽̇̐̔ͣ͢͟l̵̢̡͕̟̪̝᷿͓̦͔̝͚̦̦͚̺̝̩᷊͌ͥ̇ͫ͋ͨ̓͒̔̌ͬ̏̔̏͐̋͘͜͜͡e̸̲̞̩ͩ͆̽᷁︠̂᷁̋ͬ̎︢ͬ̾ͦ︣̔m̷̨̡̜᷿̜̦͖̞͖̪᷂̯̠̞᷂̩̩᷿̰᷂̯͒︡̎́̽́̄᷁̄͆ͬ̃̅ͤ᷇̌᷅͑͌ͤ̔̚͢͜͜͠͠͡á̵̤̲̜͉̗͎͕̺̯̗̄̈́͑ͮ̌̀͘͜͝',
// nimi ante pi kepeken lili taso (tan lipu Linku anu ante)
'wuwojiti'       : 'ẅ̴̦͓u̴̮͂̽ẅ̷̧́͜o̵̅̎͜j̵͙̟̒i̵̼͇̒̋t̸̥̐ĩ̵̥͈',
'nimisin'        : 'nimiˢⁱⁿ',
'yupekosi'       : 'y̷̨̡̧̨̢͉̭̙̥͇͍̙͇̯͔̻̙̤̹̗̦̯͎̜͂͗̚͜͜upekosi',
'kapesi'         : 'k🟫pesi',
'unu'            : '🟪nu',
'nalanja'        : 'n🟧lanja',
};
